# https://taskfile.dev

version: "3"

env:
  PYTHON_SRC: kurrawong

tasks:
  install:
    cmds:
      - poetry install

  format:
    desc: Format Python code.
    cmds:
      - poetry run ruff check --fix $PYTHON_SRC
      - poetry run ruff check --fix $PYTHON_SRC

  code:
    desc: Alias of format.
    cmds:
      - task: format

  test:
    desc: Run tests.
    cmds:
      - poetry run pytest tests -rP
